import type { Metadata } from "next";
import { Poppins, Ubuntu } from "next/font/google";
import ".././globals.css";
import NavigationBar from "../../components/navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${ubuntu.variable} antialiased w-full px-10 py-4 overflow-x-hidden`}
      >
        <section className="sticky top-5 z-50 max-w-[1200px] mx-auto">
          <NavigationBar />
        </section>
        <section className="max-w-[1200px] mx-auto">{children}</section>
      </body>
    </html>
  );
}
