import type { Metadata } from "next";
import { Poppins, Ubuntu } from "next/font/google";
import ".././globals.css";
import NavigationBar from "../components/navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${ubuntu.variable} antialiased h-screen w-full px-10 py-4 max-w-[1500px] mx-auto`}
      >
        <NavigationBar />
        <section className="mt-7">{children}</section>
      </body>
    </html>
  );
}
